# Generated by Django 3.0.8 on 2020-07-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quiz',
            new_name='quiz_polityka',
        ),
    ]
