# Generated by Django 3.0.8 on 2020-07-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200728_1909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quiz_polityka',
            new_name='Query',
        ),
    ]
