# Generated by Django 3.0.8 on 2020-07-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200728_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Question',
            new_name='Content',
        ),
    ]
