# Generated by Django 3.0.8 on 2020-07-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200728_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastFood',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
            ],
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='IQTest',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
            ],
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='PoliticalViews',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
            ],
            bases=('quiz.question',),
        ),
    ]
