# Generated by Django 3.0.8 on 2020-07-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=150)),
                ('Option1', models.CharField(max_length=150)),
                ('Option2', models.CharField(max_length=150)),
                ('Option3', models.CharField(max_length=150)),
                ('Option4', models.CharField(max_length=150)),
                ('Correct', models.CharField(max_length=150)),
            ],
        ),
    ]
