# Generated by Django 3.0.8 on 2020-08-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_fastfood_iqtest_politicalviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Correct',
        ),
        migrations.AddField(
            model_name='fastfood',
            name='Correct',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iqtest',
            name='Correct',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicalviews',
            name='BurgerAns',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicalviews',
            name='HotDogAns',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicalviews',
            name='KebabAns',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicalviews',
            name='PizzaAns',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
