# Generated by Django 3.0.8 on 2020-08-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200807_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politicalviews',
            old_name='BurgerAns',
            new_name='Ans1',
        ),
        migrations.RenameField(
            model_name='politicalviews',
            old_name='HotDogAns',
            new_name='Ans2',
        ),
        migrations.RenameField(
            model_name='politicalviews',
            old_name='KebabAns',
            new_name='Ans3',
        ),
        migrations.RenameField(
            model_name='politicalviews',
            old_name='PizzaAns',
            new_name='Ans4',
        ),
        migrations.RemoveField(
            model_name='fastfood',
            name='Correct',
        ),
        migrations.AddField(
            model_name='fastfood',
            name='Ans1',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fastfood',
            name='Ans2',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fastfood',
            name='Ans3',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fastfood',
            name='Ans4',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
